/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista_CitasMedicas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanm
 */
public class Consultar_Citas extends javax.swing.JInternalFrame {
    public Controlador_CitasMedicas.GestorCitas_Control GestorCitasControl;
    private DefaultTableModel tabla;

    /**
     * Creates new form Consultar_Citas
     */
    public Consultar_Citas() {
        initComponents();
        GestorCitasControl = new Controlador_CitasMedicas.GestorCitas_Control(this);
        String TitulosTabla[]={"N°_Identificacion" , "Nombres", "Apellidos","Fecha Cita"};
        tabla = new DefaultTableModel (null, TitulosTabla);
        Tbl_datosC.setModel(tabla);
        btn_buscarC.addActionListener(GestorCitasControl);
        buttonGroup1.add(rdb_identificacionC);
        buttonGroup1.add(rdb_nombresC);
        buttonGroup1.add(rdb_apellidosC);
        buttonGroup1.add(rdb_fechacita);
    
    }
    
     public DefaultTableModel getTableModel(){
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datosC = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        btn_buscarC = new javax.swing.JButton();
        rdb_identificacionC = new javax.swing.JRadioButton();
        rdb_nombresC = new javax.swing.JRadioButton();
        rdb_apellidosC = new javax.swing.JRadioButton();
        rdb_fechacita = new javax.swing.JRadioButton();
        CerrarC = new javax.swing.JButton();

        setTitle("Consultar Citas");

        Tbl_datosC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_datosC);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Filtro de Busqueda ");

        txt_valor.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        btn_buscarC.setBackground(new java.awt.Color(14, 242, 242));
        btn_buscarC.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btn_buscarC.setText("Buscar");
        btn_buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCActionPerformed(evt);
            }
        });

        rdb_identificacionC.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdb_identificacionC.setText("N°_Identificación");
        rdb_identificacionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_identificacionCActionPerformed(evt);
            }
        });

        rdb_nombresC.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdb_nombresC.setText("Nombres");
        rdb_nombresC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_nombresCActionPerformed(evt);
            }
        });

        rdb_apellidosC.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdb_apellidosC.setText("Apellidos");

        rdb_fechacita.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        rdb_fechacita.setText("Fecha de la Cita");

        CerrarC.setBackground(new java.awt.Color(14, 242, 242));
        CerrarC.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        CerrarC.setText("Cerrar");
        CerrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_valor, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_buscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdb_identificacionC)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_nombresC)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_apellidosC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdb_fechacita, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CerrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_identificacionC)
                    .addComponent(rdb_nombresC)
                    .addComponent(rdb_apellidosC)
                    .addComponent(rdb_fechacita))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrarC)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarCActionPerformed

    private void btn_buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarCActionPerformed

    private void rdb_identificacionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_identificacionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_identificacionCActionPerformed

    private void rdb_nombresCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_nombresCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_nombresCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CerrarC;
    public javax.swing.JTable Tbl_datosC;
    public javax.swing.JButton btn_buscarC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rdb_apellidosC;
    public javax.swing.JRadioButton rdb_fechacita;
    public javax.swing.JRadioButton rdb_identificacionC;
    public javax.swing.JRadioButton rdb_nombresC;
    public javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
