/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista_CitasMedicas;

/**
 *
 * @author juanm
 */
public class RegistroMedico extends javax.swing.JInternalFrame {
 

    private Controlador_CitasMedicas.ControlMedicos medicocontrolador;
    public RegistroMedico() {
        initComponents();
        medicocontrolador = new Controlador_CitasMedicas.ControlMedicos(this);
        RegistrarM.addActionListener(medicocontrolador);
        NuevoM.addActionListener(medicocontrolador);
        
        GrupoBotonesM.add(rdb_masculinoM);
        GrupoBotonesM.add(rdb_femeninoM);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesM = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_identificacionM = new javax.swing.JTextField();
        RegistrarM = new javax.swing.JButton();
        NuevoM = new javax.swing.JButton();
        Dtd_fecha_nacimientoM = new com.toedter.calendar.JDateChooser();
        rdb_masculinoM = new javax.swing.JRadioButton();
        rdb_femeninoM = new javax.swing.JRadioButton();
        txt_apellidosM = new javax.swing.JTextField();
        txt_nombresM = new javax.swing.JTextField();
        txt_cargomedicoM = new javax.swing.JTextField();
        CerrarM = new javax.swing.JButton();

        setTitle("Registro Medico");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("N°_Identificación ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Nombres");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Genero");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel7.setText("Cargo Medico");

        txt_identificacionM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        RegistrarM.setBackground(new java.awt.Color(14, 242, 242));
        RegistrarM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        RegistrarM.setText("Registrar");
        RegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarMActionPerformed(evt);
            }
        });

        NuevoM.setBackground(new java.awt.Color(14, 242, 242));
        NuevoM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        NuevoM.setText("Nuevo");

        rdb_masculinoM.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        rdb_masculinoM.setText("M");

        rdb_femeninoM.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        rdb_femeninoM.setText("F");

        txt_apellidosM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        txt_nombresM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        txt_cargomedicoM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        CerrarM.setBackground(new java.awt.Color(14, 242, 242));
        CerrarM.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        CerrarM.setText("Cerrar");
        CerrarM.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                CerrarMAncestorRemoved(evt);
            }
        });
        CerrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrarM)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(rdb_masculinoM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(NuevoM)
                                        .addGap(18, 18, 18)
                                        .addComponent(CerrarM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(rdb_femeninoM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_identificacionM)
                                .addComponent(txt_apellidosM)
                                .addComponent(txt_nombresM)
                                .addComponent(txt_cargomedicoM)
                                .addComponent(Dtd_fecha_nacimientoM, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_identificacionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombresM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_apellidosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cargomedicoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Dtd_fecha_nacimientoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(rdb_masculinoM)
                    .addComponent(rdb_femeninoM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarM)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NuevoM)
                        .addComponent(CerrarM)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarMActionPerformed

    private void CerrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarMActionPerformed
        
        
    }//GEN-LAST:event_CerrarMActionPerformed

    private void CerrarMAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CerrarMAncestorRemoved

    }//GEN-LAST:event_CerrarMAncestorRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CerrarM;
    public com.toedter.calendar.JDateChooser Dtd_fecha_nacimientoM;
    private javax.swing.ButtonGroup GrupoBotonesM;
    public javax.swing.JButton NuevoM;
    public javax.swing.JButton RegistrarM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton rdb_femeninoM;
    public javax.swing.JRadioButton rdb_masculinoM;
    public javax.swing.JTextField txt_apellidosM;
    public javax.swing.JTextField txt_cargomedicoM;
    public javax.swing.JTextField txt_identificacionM;
    public javax.swing.JTextField txt_nombresM;
    // End of variables declaration//GEN-END:variables
}
